### ISSUE TITLE
move over code from EU19 theme

### ISSUE THREAD

**Issue by privatemaker** [tracking-exposed/hugo-theme-trex#1]
So far @lrnzctld has made a hugo theme for the EU19 subsite which is here [eutrex](https://github.com/tracking-exposed/eu19/tree/master/themes/eutrex).

Before I push any of the theme code i have been creating I will wait for the theme Lorenzo is working on to be pushed here.

**Comment by lc-d** [comment]
right! I just try to push the generalized theme here, separated form eu19: https://github.com/tracking-exposed/hugo-theme-trex <https://github.com/tracking-exposed/hugo-theme-trex>

**Comment by lc-d** [comment]
Hi @privatemaker, I've just add a better readme to project. For any problems we can open new issues here. I'm going to close this one.
