### ISSUE TITLE
support subtitle

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/hugo-theme-trex#10]
I was looking to have a conditional subtitle, if in the header of a post is present:

```
---
title: "First write up: a labor union for content creator"
subtitle: "some subtitle here"
date: 2019-05-31T10:00:00+01:00
draft: false
layout: single
---
```

I would like it appear here:

![image](https://user-images.githubusercontent.com/89555/61449810-03f23f80-a956-11e9-94bc-2167c2a30230.png)

I made some test, but I can't reach from '_default/single.html' `{{ .Get "subtitle" }}`, not `{{ .subtitle }}`, any help?

**Comment by lc-d** [comment]
solved here: 3c69afe
