### ISSUE TITLE
re-organize folder structure like other Hugo themes

### ISSUE THREAD

**Issue by privatemaker** [tracking-exposed/hugo-theme-trex#2]
As I understand what @lrnzctld did with this folder, it is more like a starter template for a new **Tracking Exposed** sub-site (facebok., eu19., etc...). 

I think we should use this repository like how other Hugo themes are organized- where the main directory is the theme files, and there is an `exampleSite` nested in side of this. 

- [spectrum theme](https://github.com/silvanocerza/spectrum)
- [cayman theme](https://github.com/zwbetz-gh/cayman-hugo-theme)
- [coder theme](https://github.com/luizdepra/hugo-coder)

I will push an example of this re-structuring shortly.

**Comment by lrnzctld** [comment]
You are right!
I can do it, but listen to each other before.
see you later,
L.


Lorenzo Cataldi
UX/UI designer & Front-end web developer

https://cataldi.design/ <https://cataldi.design/>
+ 39 333 3508514

Questo messaggio è destinato unicamente alla/e persona/e sopraindicata/e. È strettamente personale e può contenere informazioni la cui riservatezza è tutelata dalla normativa ai sensi del DLgs 196/03. È spressamente vietato alla/e persona/e non destinataria/e leggere, copiare o comunque usare questo messaggio o diffonderne il contenuto senza autorizzazione. Chi ha ricevuto per errore questo fax o messaggio è pregato di distruggerlo e di avvertire per telefono o email, il mittente.
