### ISSUE TITLE
Create a new squared SVG asset for the logo

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/hugo-theme-trex#23]
I'm using this repo for the new version of the [web extension](https://github.com/tracking-exposed/web-extension/). The web extension needs an icon to display on its button. I see there are several `jpg` files under `static/images` of different size. I can use them, but it would be even better if I use a single `svg` file.

Can someone add a `trex-logo.svg` in that directory?

**Comment by vrde** [comment]
:woman_facepalming: warning :man_facepalming: 

This is not supported by Chrome. It's only 10 years they are talking about this: https://bugs.chromium.org/p/chromium/issues/detail?id=29683

**Comment by vrde** [comment]
Anyway, I still think it makes sense to have a pure svg logo. Feel free to merge #24 if you think it's useful.

**Comment by lc-d** [comment]
take in mind that the jpgs under `static/images` like `trex-logo-180x180.jpg` are intended to be use for web icons, take a look here: https://github.com/tracking-exposed/hugo-theme-trex/blob/master/layouts/partials/head.html

**Comment by lc-d** [comment]
There are `static/images/header-logo-default-black.svg` and `static/images/header-logo-default.svg` that maybe can help

**Comment by vrde** [comment]
> take in mind that the jpgs under `static/images` like `trex-logo-180x180.jpg` are intended to be use for web icons, take a look here: https://github.com/tracking-exposed/hugo-theme-trex/blob/master/layouts/partials/head.html

In general, I'd go for PNG for icons and logos. I've exported my own icons for the web extension.

> There are `static/images/header-logo-default-black.svg` and `static/images/header-logo-default.svg` that maybe can help

Thanks, I saw those ones, will use them for the header of the web extension.

Let me know what you think about #24.

**Comment by lc-d** [comment]
In my experience png as icon shows a black background.
