### ISSUE TITLE
decide on using Bootstrap or no

### ISSUE THREAD

**Issue by privatemaker** [tracking-exposed/hugo-theme-trex#3]
When discussing with @vecna in past days we decided to use [Bootstrap V4](https://getbootstrap.com/) for this theme.

But I see @lrnzctld has made his own [CSS structures](https://github.com/tracking-exposed/hugo-theme-trex/tree/master/themes/trex/assets/sass).

There are many pros to using Bootstrap, but also is a methodology and syntax one must learn how to do. We should discuss this before proceeding any further, as I had been working with Bootstrap previously on this theme.

**Comment by lc-d** [comment]
In my opinion I believe that bootstrap is just a waste of code but if you think that could help, go ahead. It could have impact on the theme html, so I suggest to keep bootstrap away from eu19

**Comment by lc-d** [comment]
As well argued by @privatemaker we decide to move to Bootstrap v4 in order to make easier maintainability and in order to have UI element ready to use.
