### ISSUE TITLE
unclear how I should use the partial+variable

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/hugo-theme-trex#7]
### Problem
we have different extensions, so we shouldn't be bound on promoting only one.

![image](https://user-images.githubusercontent.com/89555/61138956-af1f7680-a4c8-11e9-96cf-0f49d1bd9872.png)

**Comment by vecna** [comment]
as the commit message say, the commit above breaks the template and I don't know if the best approach is:

1. in config.toml we specify which partial should be included. home.html include the correct name
2. in config.toml we specify if we are "yt" or "fb", and get-browser-extension use this switch to trigger one link or the other
3. if home should check from config.toml and include the correct partial.

I don't know in your design which is the best pattern, but please consider:

- we might want to include fb or yt extension from every website under tracking.exposed umbrella, and have this control in the page which define the inclusion

let me know @lc-d and @privatemaker, thanks!

**Comment by lc-d** [comment]
I got it, I’m on it this monday.

**Comment by lc-d** [comment]
My idea is to make a if statement into the extension partial, where define the url value for any different sub-site, i.e.: you define "facebook" as "subsite" param in config.toml then the right url will be defined into the partial. Otherwise we can add two different params into config.toml where write the right url for the extension.

**Comment by vecna** [comment]
Thanks for this input. I was imaging something like that, but I'm skeptical because:
1) we are creating additional logic only for the sake of keeping one "home.html." I prefer to reduce logic, always. generalize is useful when we can reuse code, and the parameters become crucial to make the design quicker.

2) Why, can't build "youtube-home.html" or "facebook-home.html" which included the proper extension selectively ? I'm sure there are good reasons, but I can't say which

3) if we use the statement in config.toml, in a project such as European, or india.tracking.exposed, in which we want to promote both of the extension in different pages,

**Comment by lc-d** [comment]
The home template is unique, a solution could be to define extension variabile into the `content/_index.md` and call different partial in consequence of that

**Comment by lc-d** [comment]
i.e. we define the page params value in - facebook - youtube - both and call different partial

**Comment by vecna** [comment]
Update, the extension inclusion has been solved with proper 'shortcodes': https://github.com/tracking-exposed/hugo-theme-trex/issues/8

but I've an additional issue on design:

1. I shared https://testing.tracking.exposed/seeyou/ it is ytTREX, I realized the preview was this:
![image](https://user-images.githubusercontent.com/89555/61371854-fffee880-a895-11e9-864a-5758ee059198.png)

2.  This is not OK because should be youtube. Further investigation reveals: 
```
c:\Users\Claudio\VMShared\youtube.tracking.exposed (master)
λ grep -R "EU19" .
./themes/trex/layouts/partials/head.html:    <meta property="og:site_name" content="EU19 Tracking Exposed" />
```

The open graph might have customizable entries in every page, and only few default (defined in config.toml). If you know how to do it, please update this issue

**Comment by lc-d** [comment]
Right! I'll fix it tomorrow.

**Comment by vecna** [comment]
> 
> 
> Right! I'll fix it tomorrow.

No worries, that is fixed. I was just updating the issue before making the solution. is the commit mentioned above. thanks.
